### ISSUE TITLE
Grafana-server Init Failed

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/grafanaport#3]
Missing the default ini file?

[SYSA] bash-5.2$ which grafana
/hewitt/zopentools/zopen_repo/usr/local/bin/grafana

[SYSA] bash-5.2$ grafana --version
grafana version 11.0.0

[SYSA] bash-5.2$ grafana server
Grafana-server Init Failed: Could not find config defaults, make sure homepath command line parameter is set or working directory is homepath

**Comment by v1gnesh** [comment]
Hi Gary,

This repo has just the back-end go component.
The front-end component (website, etc.) is proving to be quite a hassle due to the dependencies, even for `linux/s390x`.
Some components are built in Rust, so it won't be possible to have the front-end working in zOS.

It may still be possible to run Grafana's back-end in zOS, and front-end in `linux/s390x`, but I can't see the value in that, over the "split-body" complexity.

**Comment by gngrossi** [comment]
Hello @v1gnesh, Sorry, I didn't realize that was/is the case. I was looking forward to running Grafana on z/OS...maybe another reason at some point for Rust on the platform. Thanks for the clarification.

I was able to run Prometheus after creating a prometheus.yml file...from what I've read it's written in go.

thanks again

**Comment by IgorTodorovskiIBM** [comment]
> This repo has just the back-end go component. The front-end component (website, etc.) is proving to be quite a hassle due to the dependencies, even for `linux/s390x`. Some components are built in Rust, so it won't be possible to have the front-end working in zOS.

Is this one of the yarn dependencies you were looking at?

**Comment by v1gnesh** [comment]
Yup, it's pretty hairy... https://github.com/nrwl/nx/discussions/23573
